### ISSUE TITLE
Add mention of icons CDN to readme?

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/icons#35]
A while back I made https://icons.dino.icu, which acts as a CDN for icons in projects that don't use React.

I could add some documentation, but the request format is pretty straightforward:
```
https://icons.dino.icu/icons/color:<Color>/glyph:<GlyphName>.svg
```
The color must be a valid SVG/HTML5 color, and the glyph must be one from the website. For example, https://icons.dino.icu/icons/color:red/glyph:clubs.svg.

![icons.dino.icu/icons/color:red/glyph:clubs.svg](https://icons.dino.icu/icons/color:red/glyph:clubs.svg)

I think it might be helpful to add a mention of the CDN to the README for future users of the Hack Club iconset. If it sounds like an interesting feature, we can add it to the README or maybe integrate it into the site itself.

**Comment by sampoder** [comment]
I love this idea! Could we get the CDN hosted on the icons.hackclub.com domain?

**Comment by YodaLightsabr** [comment]
Sure! Do you know if icons.hackclub.com is hosted on Vercel? If it is then it's as easy as copying the API functions.

**Comment by sampoder** [comment]
Yep it is!

**Comment by YodaLightsabr** [comment]
Cool, I'll work on a PR adding the API routes.
